project_id = "vnpyzhvzkkzwhbsypkej"

[functions.scrape-articles]
verify_jwt = false

[functions.cluster-startups]
verify_jwt = false

[functions.scrape-sifted-daily]
verify_jwt = false

[functions.scrape-lightpanda]
verify_jwt = false
